const DATA=window.ZUME_DATA;
const BRANDS={"ochoas":"Ochoas","ttintico":"TTintico","griplies":"Griplies","mate-topp":"Mate Topp","delicious":"Delicious For All","espiritu-andaki":"Espíritu Andakí"};
const KEY_HASHES={"__admin":"70951c3f8986fcf5ad6c9e25471d36c8bf852f7371d913e4bce18783cbb20f46","ochoas":"d7dbbd12ed8c271e35b3933fd01147fb5fd4570d619e39253e143e65a8528644","ttintico":"a17a92344dae9b462c29e8e518509f4a9f2a1ca2b931aa9fc8f34a1b65a4cf16","griplies":"da0a5de9a6c3bd73addb92d9cdbf995240e132d34b441fc4a20f7a9c368346d6","mate-topp":"9b69e44c7d917223ca4d78403530e46961869968f9bd076ca027bc3648e81e73","delicious":"3b6084a3586f81247ed3edd20aa3fbc695d1201d6a94da0c510b01a57ce4e4ef","espiritu-andaki":"194777c71b8dde2d289177b1c22e6809b8af45d30b4b226c7eb45f11200b0e91"};
let role=null,currentBrand=null;
const q=new URLSearchParams(location.search),adminMode=q.get("admin")==="1";
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function fillBrandSelect(el){el.innerHTML=Object.entries(BRANDS).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join("");}
fillBrandSelect($("loginBrand"));fillBrandSelect($("adminBrand"));
if(q.get("brand")&&BRANDS[q.get("brand")])$("loginBrand").value=q.get("brand");
if(adminMode){$("brandLoginFields").classList.add("hidden");$("loginTitle").textContent="Admin · ZUME";$("loginText").textContent="Ingresá la clave de administración.";}
async function sha256(text){const data=new TextEncoder().encode(text);const digest=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("");}
$("loginBtn").onclick=async()=>{$("loginError").textContent="";$("loginBtn").disabled=true;const key=$("loginKey").value.trim();const brand=$("loginBrand").value;const hash=await sha256(key);$("loginBtn").disabled=false;if(adminMode){if(hash!==KEY_HASHES.__admin){$("loginError").textContent="Clave incorrecta.";return}role="admin";currentBrand=q.get("brand")&&BRANDS[q.get("brand")]?q.get("brand"):"ochoas";}else{if(hash!==KEY_HASHES[brand]){$("loginError").textContent="Marca o clave incorrecta.";return}role="client";currentBrand=brand;}sessionStorage.setItem("zumePortalSession",JSON.stringify({role,brand:currentBrand}));showApp();};
$("loginKey").addEventListener("keydown",e=>{if(e.key==="Enter")$("loginBtn").click()});
function checkSession(){try{const s=JSON.parse(sessionStorage.getItem("zumePortalSession")||"null");if(!s)return;if(adminMode&&s.role!=="admin")return;if(!adminMode&&s.role!=="client")return;role=s.role;currentBrand=s.role==="admin"?(q.get("brand")&&BRANDS[q.get("brand")]?q.get("brand"):s.brand||"ochoas"):s.brand;if(!BRANDS[currentBrand])return;showApp();}catch{}}
function showApp(){$("login").classList.add("hidden");$("top").classList.remove("hidden");$("app").classList.remove("hidden");$("footer").classList.remove("hidden");if(role==="admin"){$("adminBrand").classList.remove("hidden");$("adminBrand").value=currentBrand;$("sourcesPanel").classList.remove("hidden");}else{$("adminBrand").classList.add("hidden");$("sourcesPanel").classList.add("hidden");}render();}
$("adminBrand").onchange=e=>{currentBrand=e.target.value;sessionStorage.setItem("zumePortalSession",JSON.stringify({role:"admin",brand:currentBrand}));history.replaceState(null,"",`?admin=1&brand=${currentBrand}`);render();};
$("logoutBtn").onclick=()=>{sessionStorage.removeItem("zumePortalSession");location.href="/planificador/";};
$("adminFooter").onclick=()=>{sessionStorage.removeItem("zumePortalSession");location.href="/planificador/?admin=1";};
function render(){const d=DATA[currentBrand]||{name:BRANDS[currentBrand],month:"",sources:{},rules:"",posts:[],photos:[],reels:[],stories:[]};$("currentLabel").textContent=`${d.name} · ${d.month||""}`;$("heroTitle").textContent=`${d.name} · Planificador visual`;$("heroSub").textContent=d.month?`${d.month} · POST · Historias · Fotos · Reels`:"Contenido de la marca";if(role==="admin")renderSources(d);renderGrid("posts",d.posts||[]);renderGrid("photos",d.photos||[]);renderGrid("reels",d.reels||[]);renderGrid("stories",d.stories||[]);$("postsDesc").textContent=(d.posts?.length||0)+" piezas";$("photosDesc").textContent=(d.photos?.length||0)+" archivos";$("reelsDesc").textContent=(d.reels?.length||0)+" videos";$("storiesDesc").textContent=(d.stories?.length||0)+" historias";}
function renderSources(d){const s=d.sources||{};$("srcPosts").value=s.canvaPosts||"";$("srcStories").value=s.canvaStories||"";$("srcPhotos").value=s.drivePhotos||"";$("srcReels").value=s.driveReels||"";$("srcRules").value=d.rules||"";const links=[["Canva POST",s.canvaPosts],["Canva Historias",s.canvaStories],["Drive Fotos",s.drivePhotos],["Drive Reels",s.driveReels]].filter(x=>x[1]);$("sourceButtons").innerHTML=links.map(x=>`<a class="btn" href="${esc(x[1])}" target="_blank" rel="noopener">${esc(x[0])} ↗</a>`).join("");}
function renderGrid(type,items){const grid=$(type+"Grid");if(!items.length){grid.innerHTML=`<div class="empty" style="grid-column:1/-1">Todavía no hay contenido cargado para esta sección.</div>`;return}grid.innerHTML=items.map((it,i)=>cardHTML(type,it,i)).join("");grid.querySelectorAll(".card").forEach((el,i)=>{el.onclick=e=>{if(e.target.closest("a,button"))return;openItem(items[i])};});}
function cardHTML(type,it,i){const cls=type==="posts"?"post":type==="photos"?"photo":type==="stories"?"story":"reel";const tag=type==="posts"?"POST · CANVA":type==="photos"?"DRIVE · FOTO":type==="stories"?"HISTORIA · CANVA":"DRIVE · REEL";const play=type==="reels"?'<span class="play">▶</span>':"";const date=it.date?`<div class="meta">Programar: ${esc(it.date)}</div>`:"";const copy=it.copy?`<div class="copy">${esc(it.copy)}</div>`:"";const view=type==="reels"?`<button class="primary" onclick='event.stopPropagation();playReel(${JSON.stringify(it.embed)})'>▶ Ver</button>`:"";return `<article class="card ${cls}"><div class="media"><img src="${esc(it.preview)}" alt="${esc(it.title)}" loading="lazy"><span class="media-tag">${tag}</span>${play}</div><div class="body"><div class="title">${esc(it.title)}</div>${date}${copy}<div class="actions">${view}<a href="${esc(it.open)}" target="_blank" rel="noopener">Abrir ↗</a>${type!=="reels"?`<button onclick='event.stopPropagation();downloadOne(${JSON.stringify(it.preview)},${JSON.stringify(fileName(it))})'>↓ Descargar</button>`:""}</div></div></article>`;}
function fileName(it){const d=it.date||"sin-fecha";return `${(DATA[currentBrand]?.name||currentBrand).replace(/\s+/g,"_")}_${d}_${it.title.replace(/[^a-zA-Z0-9_-]+/g,"_")}.jpg`;}
function openItem(it){if(it.type==="reel"){playReel(it.embed);return}$("modalContent").innerHTML=`<img class="modal-preview" src="${esc(it.preview)}"><h3>${esc(it.title)}</h3>${it.date?`<p><b>Fecha de programación:</b> ${esc(it.date)}</p>`:""}${it.copy?`<div class="copy">${esc(it.copy)}</div>`:""}<div class="actions"><a href="${esc(it.open)}" target="_blank" rel="noopener">Abrir original ↗</a><button class="primary" id="modalDownload">↓ Descargar</button></div>`;$("modal").classList.add("open");setTimeout(()=>{const b=$("modalDownload");if(b)b.onclick=()=>downloadOne(it.preview,fileName(it));},0);}
function playReel(url){$("modalContent").innerHTML=`<iframe class="modal-video" src="${esc(url)}" allow="autoplay; fullscreen" allowfullscreen></iframe>`;$("modal").classList.add("open");}
$("modalClose").onclick=()=>{$("modal").classList.remove("open");$("modalContent").innerHTML=""};$("modal").onclick=e=>{if(e.target===$("modal"))$("modalClose").click()};
async function getBlob(url){const r=await fetch(url);if(!r.ok)throw new Error("download");return await r.blob();}
async function downloadOne(url,name){try{const b=await getBlob(url),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}catch{window.open(url,"_blank")}}
document.querySelectorAll("[data-bulk]").forEach(btn=>btn.onclick=async()=>{const type=btn.dataset.bulk,items=DATA[currentBrand]?.[type]||[];if(!items.length)return;const old=btn.textContent;btn.disabled=true;try{if("showDirectoryPicker"in window){const dir=await window.showDirectoryPicker({mode:"readwrite"});let n=0;for(const it of items){btn.textContent=`Guardando ${++n}/${items.length}`;const blob=await getBlob(it.preview),h=await dir.getFileHandle(fileName(it),{create:true}),w=await h.createWritable();await w.write(blob);await w.close()}btn.textContent="Guardadas ✓"}else{for(const it of items){await downloadOne(it.preview,fileName(it));await new Promise(r=>setTimeout(r,250))}}}catch(e){console.error(e);alert("El navegador no pudo descargar alguna pieza directamente. Podés abrirla y descargarla desde su fuente.")}finally{setTimeout(()=>{btn.textContent=old;btn.disabled=false},1200)}});
checkSession();